# Generated by Codex on 2026-07-08

import django.db.models.deletion
from django.db import migrations, models


def backfill_business(apps, schema_editor):
    Business = apps.get_model("accounts", "Business")
    ExpenseCategory = apps.get_model("finance", "ExpenseCategory")
    Invoice = apps.get_model("finance", "Invoice")
    Expense = apps.get_model("finance", "Expense")
    CapitalInjection = apps.get_model("finance", "CapitalInjection")
    business = Business.objects.order_by("id").first()
    if business:
        ExpenseCategory.objects.filter(business__isnull=True).update(business=business)
        Invoice.objects.filter(business__isnull=True).update(business=business)
        Expense.objects.filter(business__isnull=True).update(business=business)
        CapitalInjection.objects.filter(business__isnull=True).update(business=business)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_business_membership"),
        ("finance", "0002_invoice_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensecategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="business",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="expense_categories", to="accounts.business"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="business",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="accounts.business"),
        ),
        migrations.AddField(
            model_name="expense",
            name="business",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="expenses", to="accounts.business"),
        ),
        migrations.AddField(
            model_name="capitalinjection",
            name="business",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="capital_injections", to="accounts.business"),
        ),
        migrations.AlterUniqueTogether(
            name="expensecategory",
            unique_together={("name", "business")},
        ),
        migrations.RunPython(backfill_business, migrations.RunPython.noop),
    ]
