# Generated by Codex on 2026-07-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_business_membership"),
        ("finance", "0003_business_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryExpenseItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("industry", models.CharField(help_text="e.g. Restaurant, Construction, Retail", max_length=120)),
                ("name", models.CharField(help_text="e.g. Food inventory, jobsite fuel, packaging supplies", max_length=160)),
                ("default_notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("business", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="industry_expense_items", to="accounts.business")),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="industry_items", to="finance.expensecategory")),
            ],
            options={
                "ordering": ["industry", "name"],
                "unique_together": {("business", "industry", "name")},
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="industry_item",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="expenses", to="finance.industryexpenseitem"),
        ),
    ]
