# Generated by Codex on 2026-07-08

import django.conf
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(django.conf.settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("MANAGER", "Manager"), ("USER", "User")], default="USER", max_length=20)),
                ("can_access_projects", models.BooleanField(default=False)),
                ("can_access_documents", models.BooleanField(default=False)),
                ("can_access_vendors", models.BooleanField(default=False)),
                ("can_access_finance", models.BooleanField(default=False)),
                ("can_manage_accounts", models.BooleanField(default=False)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="profile", to=django.conf.settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
