# Generated by Codex on 2026-07-08

import django.conf
import django.db.models.deletion
from django.db import migrations, models


def create_default_business(apps, schema_editor):
    Business = apps.get_model("accounts", "Business")
    UserProfile = apps.get_model("accounts", "UserProfile")
    BusinessMembership = apps.get_model("accounts", "BusinessMembership")
    business, _ = Business.objects.get_or_create(
        name="Dowitz Workspace",
        defaults={
            "display_name": "Dowitz",
            "country": "United States",
            "default_currency": "USD",
            "invoice_prefix": "DOW",
        },
    )
    for profile in UserProfile.objects.filter(role="MANAGER"):
        membership, _ = BusinessMembership.objects.get_or_create(user_id=profile.user_id, business=business)
        membership.can_access_projects = True
        membership.can_access_documents = True
        membership.can_access_vendors = True
        membership.can_access_finance = True
        membership.can_manage_accounts = True
        membership.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(django.conf.settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("display_name", models.CharField(blank=True, max_length=160)),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                ("address_line1", models.CharField(blank=True, max_length=160)),
                ("address_line2", models.CharField(blank=True, max_length=160)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="United States", max_length=100)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("tax_id", models.CharField(blank=True, max_length=80)),
                ("default_currency", models.CharField(default="USD", max_length=3)),
                ("fiscal_year_start_month", models.PositiveSmallIntegerField(default=1)),
                ("invoice_prefix", models.CharField(blank=True, max_length=20)),
                ("brand_color", models.CharField(default="#6366f1", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="BusinessMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("can_access_projects", models.BooleanField(default=False)),
                ("can_access_documents", models.BooleanField(default=False)),
                ("can_access_vendors", models.BooleanField(default=False)),
                ("can_access_finance", models.BooleanField(default=False)),
                ("can_manage_accounts", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="accounts.business")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="business_memberships", to=django.conf.settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["business__name", "user__username"], "unique_together": {("user", "business")}},
        ),
        migrations.RunPython(create_default_business, migrations.RunPython.noop),
    ]
