# Generated by Codex on 2026-07-08

import django.db.models.deletion
from django.db import migrations, models


def backfill_business(apps, schema_editor):
    Business = apps.get_model("accounts", "Business")
    Document = apps.get_model("documents", "Document")
    business = Business.objects.order_by("id").first()
    if business:
        Document.objects.filter(business__isnull=True).update(business=business)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_business_membership"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="business",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="accounts.business"),
        ),
        migrations.RunPython(backfill_business, migrations.RunPython.noop),
    ]
