# Generated by Django 6.0.5 on 2026-05-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendorservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.CharField(blank=True, help_text='Short description of what the company does at a glance.', max_length=255),
        ),
    ]
