# Generated by Codex on 2026-07-08

import django.db.models.deletion
from django.db import migrations, models


def backfill_business(apps, schema_editor):
    Business = apps.get_model("accounts", "Business")
    Vendor = apps.get_model("vendors", "Vendor")
    VendorTag = apps.get_model("vendors", "VendorTag")
    business = Business.objects.order_by("id").first()
    if business:
        Vendor.objects.filter(business__isnull=True).update(business=business)
        VendorTag.objects.filter(business__isnull=True).update(business=business)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_business_membership"),
        ("vendors", "0003_vendor_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendortag",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name="vendor",
            name="business",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="vendors", to="accounts.business"),
        ),
        migrations.AddField(
            model_name="vendortag",
            name="business",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="vendor_tags", to="accounts.business"),
        ),
        migrations.AlterUniqueTogether(
            name="vendortag",
            unique_together={("name", "business")},
        ),
        migrations.RunPython(backfill_business, migrations.RunPython.noop),
    ]
