# Generated by Codex on 2026-07-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_industry_expense_items"),
        ("vendors", "0004_vendor_business"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="default_expense_category",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="default_vendors", to="finance.expensecategory"),
        ),
        migrations.AddField(
            model_name="vendor",
            name="default_industry_item",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="default_vendors", to="finance.industryexpenseitem"),
        ),
    ]
